# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.data_response import DataResponse
from .raw_client import AsyncRawKnowledgeClient, RawKnowledgeClient
from .types.find_artifact_request_kind import FindArtifactRequestKind
from .types.get_brief_request_kind import GetBriefRequestKind
from .types.list_conflicts_request_status import ListConflictsRequestStatus
from .types.list_findings_request_sort import ListFindingsRequestSort
from .types.list_findings_request_source import ListFindingsRequestSource
from .types.list_findings_request_type import ListFindingsRequestType
from .types.list_tasks_request_owner import ListTasksRequestOwner
from .types.list_tasks_request_status import ListTasksRequestStatus
from .types.search_knowledge_request_type import SearchKnowledgeRequestType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class KnowledgeClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawKnowledgeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawKnowledgeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawKnowledgeClient
        """
        return self._raw_client

    def suggest_vault_scope(
        self, *, conversation: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        Resolve the minimum safe vault scope from the user's recent conversation, using only this API key holder's authorized vault names, keywords, known people and cached summaries. Call it after list_vaults when the right vault is not explicit. Returns selected vault ids or a focused clarification question; it does not search vault content.

        Parameters
        ----------
        conversation : str
            The recent user conversation that identifies a client, project, person or topic (maximum 12,000 trailing characters used).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Suggest Vault Scope completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.suggest_vault_scope(
            conversation="conversation",
        )
        """
        _response = self._raw_client.suggest_vault_scope(conversation=conversation, request_options=request_options)
        return _response.data

    def search_knowledge(
        self,
        *,
        query: str,
        vault: typing.Optional[str] = OMIT,
        type: typing.Optional[SearchKnowledgeRequestType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Search the discovery knowledge base (departments, people, processes, systems, problems, opportunities, KPIs) by name or alias. Returns matching entities with descriptions.

        Parameters
        ----------
        query : str
            Name or alias to search for

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        type : typing.Optional[SearchKnowledgeRequestType]
            Optional entity type filter

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Search Knowledge completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.search_knowledge(
            query="query",
        )
        """
        _response = self._raw_client.search_knowledge(
            query=query, vault=vault, type=type, request_options=request_options
        )
        return _response.data

    def get_entity(
        self,
        *,
        entity_id: str,
        vault: typing.Optional[str] = OMIT,
        include_evidence: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Get one entity in depth: core fields (description, aliases, recency) plus slim deduped graph edges ({entityId, name, type, relation, direction, weight}. weight = number of co-mentions across meetings). Set includeEvidence=true to also get the verbatim quotes (who said it, in which meeting). A conflicts array appears when the evidence contains contradictory claims needing validation.

        Parameters
        ----------
        entity_id : str
            Entity id from a previous call

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        include_evidence : typing.Optional[bool]
            Include verbatim evidence quotes (default false)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Get Entity completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.get_entity(
            entity_id="entityId",
        )
        """
        _response = self._raw_client.get_entity(
            entity_id=entity_id, vault=vault, include_evidence=include_evidence, request_options=request_options
        )
        return _response.data

    def search_transcripts(
        self, *, query: str, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        Semantic search over the meeting transcripts. Returns the most relevant verbatim excerpts with speakers and meeting names.

        Parameters
        ----------
        query : str
            What to look for

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Search Transcripts completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.search_transcripts(
            query="query",
        )
        """
        _response = self._raw_client.search_transcripts(query=query, vault=vault, request_options=request_options)
        return _response.data

    def list_meetings(
        self, *, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        List the discovery meetings (name, date, attendees, extraction status).

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Meetings completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.list_meetings()
        """
        _response = self._raw_client.list_meetings(vault=vault, request_options=request_options)
        return _response.data

    def list_calendar(
        self, *, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        Project calendar events, recent (45 days back) and scheduled ahead: title, ISO datetime, a happened flag, attendees, Meet link. Cross with list_meetings (recorded) to distinguish what already happened from what is merely booked.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Calendar completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.list_calendar()
        """
        _response = self._raw_client.list_calendar(vault=vault, request_options=request_options)
        return _response.data

    def get_meeting(
        self,
        *,
        meeting_id: str,
        vault: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Get one meeting: metadata, notes (markdown), and the entities extracted from it (with per-meeting mention counts). use it to answer 'what came out of meeting X'.

        Parameters
        ----------
        meeting_id : str
            Meeting id from list_meetings

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Get Meeting completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.get_meeting(
            meeting_id="meetingId",
        )
        """
        _response = self._raw_client.get_meeting(meeting_id=meeting_id, vault=vault, request_options=request_options)
        return _response.data

    def list_findings(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        type: typing.Optional[ListFindingsRequestType] = OMIT,
        source: typing.Optional[ListFindingsRequestSource] = OMIT,
        meeting_id: typing.Optional[str] = OMIT,
        sort: typing.Optional[ListFindingsRequestSort] = OMIT,
        limit: typing.Optional[float] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        compact: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Paginated findings inventory. Filters: type, source, meetingId (only entities from that meeting). sort: 'mentions' (default) or 'recent' (by lastMentionedAt). compact=true returns only {id, name, type, mentionCount, lastMentionedAt}. recommended for orientation; fetch details with get_entity. Returns {findings, total, nextCursor}.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        type : typing.Optional[ListFindingsRequestType]

        source : typing.Optional[ListFindingsRequestSource]

        meeting_id : typing.Optional[str]
            Only entities with evidence from this meeting

        sort : typing.Optional[ListFindingsRequestSort]

        limit : typing.Optional[float]
            Page size (default 50, max 200)

        cursor : typing.Optional[str]
            nextCursor from the previous page

        compact : typing.Optional[bool]
            Slim payload (default false)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Findings completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.list_findings()
        """
        _response = self._raw_client.list_findings(
            vault=vault,
            type=type,
            source=source,
            meeting_id=meeting_id,
            sort=sort,
            limit=limit,
            cursor=cursor,
            compact=compact,
            request_options=request_options,
        )
        return _response.data

    def list_tasks(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        owner: typing.Optional[ListTasksRequestOwner] = OMIT,
        status: typing.Optional[ListTasksRequestStatus] = OMIT,
        milestone_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Action-plan tasks with the full board surface: id (for update_task), board identifier, t-shirt estimate, priority, labels, checklist, due date and milestone. owner "us" = our team, "client" = the counterparty; status "open" = everything not done.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        owner : typing.Optional[ListTasksRequestOwner]

        status : typing.Optional[ListTasksRequestStatus]

        milestone_id : typing.Optional[str]
            Only tasks in this milestone (id from list_milestones)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Tasks completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.list_tasks()
        """
        _response = self._raw_client.list_tasks(
            vault=vault, owner=owner, status=status, milestone_id=milestone_id, request_options=request_options
        )
        return _response.data

    def list_files(
        self, *, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        List the project's PUBLIC files (name, description, download URL). Internal files are never served here. Give the URL to the user as a link when they ask for a file.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Files completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.list_files()
        """
        _response = self._raw_client.list_files(vault=vault, request_options=request_options)
        return _response.data

    def get_file(
        self,
        *,
        file_id: str,
        vault: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Get one PUBLIC file: metadata, a temporary download URL, and a content excerpt when the file was parsed.

        Parameters
        ----------
        file_id : str
            File id from list_files

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Get File completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.get_file(
            file_id="fileId",
        )
        """
        _response = self._raw_client.get_file(file_id=file_id, vault=vault, request_options=request_options)
        return _response.data

    def list_plan_steps(
        self, *, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        The mutual action plan timeline (macro project steps, status, and whether each was proposed by the agent or a person).

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Plan Steps completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.list_plan_steps()
        """
        _response = self._raw_client.list_plan_steps(vault=vault, request_options=request_options)
        return _response.data

    def changes_since(
        self, *, since: str, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        What's new since a given moment: entities first seen after it, entities re-mentioned after it, and new meetings. The natural 'what changed since we last talked' call.

        Parameters
        ----------
        since : str
            ISO 8601 datetime, e.g. 2026-07-18T00:00:00Z

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Changes Since completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.changes_since(
            since="since",
        )
        """
        _response = self._raw_client.changes_since(since=since, vault=vault, request_options=request_options)
        return _response.data

    def stats(
        self, *, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        Cheap orientation: entity counts by type, meetings extracted/total, tasks by status. Call this first to size the knowledge base.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Stats completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.stats()
        """
        _response = self._raw_client.stats(vault=vault, request_options=request_options)
        return _response.data

    def get_brief(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        kind: typing.Optional[GetBriefRequestKind] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        The latest agent-written brief. kind 'daily' (default) is the current 'what's going on' snapshot of the vault; 'weekly-plan' and 'weekly-digest' mirror the Monday plan and Friday digest e-mails. Good second call after stats for orientation.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        kind : typing.Optional[GetBriefRequestKind]
            Which brief (default daily)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Get Brief completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.get_brief()
        """
        _response = self._raw_client.get_brief(vault=vault, kind=kind, request_options=request_options)
        return _response.data

    def get_transcript(
        self,
        *,
        meeting_id: str,
        vault: typing.Optional[str] = OMIT,
        offset: typing.Optional[float] = OMIT,
        limit: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Read a meeting transcript sequentially in chunks (complements semantic search). Returns {chunks: [{index, speakers, text}], totalChunks, nextOffset}.

        Parameters
        ----------
        meeting_id : str
            Meeting id from list_meetings

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        offset : typing.Optional[float]
            Chunk offset (default 0)

        limit : typing.Optional[float]
            Chunks per page (default 20, max 50)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Get Transcript completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.get_transcript(
            meeting_id="meetingId",
        )
        """
        _response = self._raw_client.get_transcript(
            meeting_id=meeting_id, vault=vault, offset=offset, limit=limit, request_options=request_options
        )
        return _response.data

    def list_conflicts(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        status: typing.Optional[ListConflictsRequestStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Contradictions detected across the evidence: pairs of credible claims about the same entity that cannot both be true (with speakers and meetings). Default shows open ones needing client validation; filter by status or 'all' to see resolved/dismissed history with notes. Use the id with resolve_conflict.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        status : typing.Optional[ListConflictsRequestStatus]
            Which conflicts (default open)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Conflicts completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.list_conflicts()
        """
        _response = self._raw_client.list_conflicts(vault=vault, status=status, request_options=request_options)
        return _response.data

    def list_milestones(
        self, *, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        Project milestones with task tallies (id, title, target date, tasks done/total). Use to resolve milestone ids before add_task/update_task, or to answer 'what's left in milestone X'.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Milestones completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.list_milestones()
        """
        _response = self._raw_client.list_milestones(vault=vault, request_options=request_options)
        return _response.data

    def find_person(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        query: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Look someone up in this vault's people registry: name, e-mail, title, organisation. The ONLY authoritative source for an address. never guess one or assume a pattern like first.last@company.com.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        query : typing.Optional[str]
            Name, address or role fragment

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Find Person completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.find_person()
        """
        _response = self._raw_client.find_person(vault=vault, query=query, request_options=request_options)
        return _response.data

    def list_sent_emails(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        to: typing.Optional[str] = OMIT,
        limit: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Messages this vault's agent already sent, newest first, with the handles needed to reply INSIDE the same conversation (replyToThreadId, inReplyToMessageId). Pass one back to send_email so a reply threads instead of starting a parallel conversation.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        to : typing.Optional[str]
            Narrow to one recipient

        limit : typing.Optional[float]
            1-25, default 10

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Sent Emails completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.list_sent_emails()
        """
        _response = self._raw_client.list_sent_emails(vault=vault, to=to, limit=limit, request_options=request_options)
        return _response.data

    def find_email_thread(
        self,
        *,
        query: str,
        vault: typing.Optional[str] = OMIT,
        limit: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Search the vault's connected Gmail for an existing conversation, including mail sent before this deployment started logging. Gmail search syntax, e.g. "to:ana@client.com inventory" or "subject:report newer_than:7d". Returns thread ids for send_email's replyToThreadId.

        Parameters
        ----------
        query : str
            Gmail search syntax

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        limit : typing.Optional[float]
            1-20, default 5

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Find Email Thread completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.find_email_thread(
            query="query",
        )
        """
        _response = self._raw_client.find_email_thread(
            query=query, vault=vault, limit=limit, request_options=request_options
        )
        return _response.data

    def find_artifact(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        query: typing.Optional[str] = OMIT,
        kind: typing.Optional[FindArtifactRequestKind] = OMIT,
        limit: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Find a file that already exists in this vault: something the agent generated (chart, workbook, CSV, report) or a document a member added. Search by title, newest first. Use it BEFORE rebuilding anything, and to get the artifactId that send_email attaches.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        query : typing.Optional[str]
            Words from the title. Omit to list the most recent.

        kind : typing.Optional[FindArtifactRequestKind]
            Narrow to one kind of file

        limit : typing.Optional[float]
            1-25, default 10

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Find Artifact completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.find_artifact()
        """
        _response = self._raw_client.find_artifact(
            vault=vault, query=query, kind=kind, limit=limit, request_options=request_options
        )
        return _response.data

    def search_agent_memory(
        self,
        *,
        query: str,
        vault: typing.Optional[str] = OMIT,
        person_email: typing.Optional[str] = OMIT,
        limit: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Search the agent's OWN past conversations in this vault. e-mail, MCP and portal chat. for what was already asked, answered or decided. This is conversation history, NOT the knowledge base: use search_knowledge or search_transcripts for what was said in meetings.

        Parameters
        ----------
        query : str
            What was talked about

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        person_email : typing.Optional[str]
            Narrow to exchanges with one person

        limit : typing.Optional[float]
            1-25, default 12

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Search Agent Memory completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.search_agent_memory(
            query="query",
        )
        """
        _response = self._raw_client.search_agent_memory(
            query=query, vault=vault, person_email=person_email, limit=limit, request_options=request_options
        )
        return _response.data

    def expand_graph(
        self,
        *,
        entity_id: str,
        vault: typing.Optional[str] = OMIT,
        depth: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Graph traversal from an entity: depth 1 = its slim edges; depth 2 = neighborhood expansion (capped at 120 edges, second-hop relations prefixed with the intermediate node). Use to explore paths between areas.

        Parameters
        ----------
        entity_id : str
            Starting entity id

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        depth : typing.Optional[float]
            1 or 2 (default 1)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Expand Graph completed.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.knowledge.expand_graph(
            entity_id="entityId",
        )
        """
        _response = self._raw_client.expand_graph(
            entity_id=entity_id, vault=vault, depth=depth, request_options=request_options
        )
        return _response.data


class AsyncKnowledgeClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawKnowledgeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawKnowledgeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawKnowledgeClient
        """
        return self._raw_client

    async def suggest_vault_scope(
        self, *, conversation: str, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        Resolve the minimum safe vault scope from the user's recent conversation, using only this API key holder's authorized vault names, keywords, known people and cached summaries. Call it after list_vaults when the right vault is not explicit. Returns selected vault ids or a focused clarification question; it does not search vault content.

        Parameters
        ----------
        conversation : str
            The recent user conversation that identifies a client, project, person or topic (maximum 12,000 trailing characters used).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Suggest Vault Scope completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.suggest_vault_scope(
                conversation="conversation",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.suggest_vault_scope(
            conversation=conversation, request_options=request_options
        )
        return _response.data

    async def search_knowledge(
        self,
        *,
        query: str,
        vault: typing.Optional[str] = OMIT,
        type: typing.Optional[SearchKnowledgeRequestType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Search the discovery knowledge base (departments, people, processes, systems, problems, opportunities, KPIs) by name or alias. Returns matching entities with descriptions.

        Parameters
        ----------
        query : str
            Name or alias to search for

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        type : typing.Optional[SearchKnowledgeRequestType]
            Optional entity type filter

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Search Knowledge completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.search_knowledge(
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_knowledge(
            query=query, vault=vault, type=type, request_options=request_options
        )
        return _response.data

    async def get_entity(
        self,
        *,
        entity_id: str,
        vault: typing.Optional[str] = OMIT,
        include_evidence: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Get one entity in depth: core fields (description, aliases, recency) plus slim deduped graph edges ({entityId, name, type, relation, direction, weight}. weight = number of co-mentions across meetings). Set includeEvidence=true to also get the verbatim quotes (who said it, in which meeting). A conflicts array appears when the evidence contains contradictory claims needing validation.

        Parameters
        ----------
        entity_id : str
            Entity id from a previous call

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        include_evidence : typing.Optional[bool]
            Include verbatim evidence quotes (default false)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Get Entity completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.get_entity(
                entity_id="entityId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_entity(
            entity_id=entity_id, vault=vault, include_evidence=include_evidence, request_options=request_options
        )
        return _response.data

    async def search_transcripts(
        self, *, query: str, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        Semantic search over the meeting transcripts. Returns the most relevant verbatim excerpts with speakers and meeting names.

        Parameters
        ----------
        query : str
            What to look for

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Search Transcripts completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.search_transcripts(
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_transcripts(query=query, vault=vault, request_options=request_options)
        return _response.data

    async def list_meetings(
        self, *, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        List the discovery meetings (name, date, attendees, extraction status).

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Meetings completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.list_meetings()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_meetings(vault=vault, request_options=request_options)
        return _response.data

    async def list_calendar(
        self, *, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        Project calendar events, recent (45 days back) and scheduled ahead: title, ISO datetime, a happened flag, attendees, Meet link. Cross with list_meetings (recorded) to distinguish what already happened from what is merely booked.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Calendar completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.list_calendar()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_calendar(vault=vault, request_options=request_options)
        return _response.data

    async def get_meeting(
        self,
        *,
        meeting_id: str,
        vault: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Get one meeting: metadata, notes (markdown), and the entities extracted from it (with per-meeting mention counts). use it to answer 'what came out of meeting X'.

        Parameters
        ----------
        meeting_id : str
            Meeting id from list_meetings

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Get Meeting completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.get_meeting(
                meeting_id="meetingId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_meeting(
            meeting_id=meeting_id, vault=vault, request_options=request_options
        )
        return _response.data

    async def list_findings(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        type: typing.Optional[ListFindingsRequestType] = OMIT,
        source: typing.Optional[ListFindingsRequestSource] = OMIT,
        meeting_id: typing.Optional[str] = OMIT,
        sort: typing.Optional[ListFindingsRequestSort] = OMIT,
        limit: typing.Optional[float] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        compact: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Paginated findings inventory. Filters: type, source, meetingId (only entities from that meeting). sort: 'mentions' (default) or 'recent' (by lastMentionedAt). compact=true returns only {id, name, type, mentionCount, lastMentionedAt}. recommended for orientation; fetch details with get_entity. Returns {findings, total, nextCursor}.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        type : typing.Optional[ListFindingsRequestType]

        source : typing.Optional[ListFindingsRequestSource]

        meeting_id : typing.Optional[str]
            Only entities with evidence from this meeting

        sort : typing.Optional[ListFindingsRequestSort]

        limit : typing.Optional[float]
            Page size (default 50, max 200)

        cursor : typing.Optional[str]
            nextCursor from the previous page

        compact : typing.Optional[bool]
            Slim payload (default false)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Findings completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.list_findings()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_findings(
            vault=vault,
            type=type,
            source=source,
            meeting_id=meeting_id,
            sort=sort,
            limit=limit,
            cursor=cursor,
            compact=compact,
            request_options=request_options,
        )
        return _response.data

    async def list_tasks(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        owner: typing.Optional[ListTasksRequestOwner] = OMIT,
        status: typing.Optional[ListTasksRequestStatus] = OMIT,
        milestone_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Action-plan tasks with the full board surface: id (for update_task), board identifier, t-shirt estimate, priority, labels, checklist, due date and milestone. owner "us" = our team, "client" = the counterparty; status "open" = everything not done.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        owner : typing.Optional[ListTasksRequestOwner]

        status : typing.Optional[ListTasksRequestStatus]

        milestone_id : typing.Optional[str]
            Only tasks in this milestone (id from list_milestones)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Tasks completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.list_tasks()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_tasks(
            vault=vault, owner=owner, status=status, milestone_id=milestone_id, request_options=request_options
        )
        return _response.data

    async def list_files(
        self, *, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        List the project's PUBLIC files (name, description, download URL). Internal files are never served here. Give the URL to the user as a link when they ask for a file.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Files completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.list_files()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_files(vault=vault, request_options=request_options)
        return _response.data

    async def get_file(
        self,
        *,
        file_id: str,
        vault: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Get one PUBLIC file: metadata, a temporary download URL, and a content excerpt when the file was parsed.

        Parameters
        ----------
        file_id : str
            File id from list_files

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Get File completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.get_file(
                file_id="fileId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_file(file_id=file_id, vault=vault, request_options=request_options)
        return _response.data

    async def list_plan_steps(
        self, *, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        The mutual action plan timeline (macro project steps, status, and whether each was proposed by the agent or a person).

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Plan Steps completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.list_plan_steps()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_plan_steps(vault=vault, request_options=request_options)
        return _response.data

    async def changes_since(
        self, *, since: str, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        What's new since a given moment: entities first seen after it, entities re-mentioned after it, and new meetings. The natural 'what changed since we last talked' call.

        Parameters
        ----------
        since : str
            ISO 8601 datetime, e.g. 2026-07-18T00:00:00Z

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Changes Since completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.changes_since(
                since="since",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.changes_since(since=since, vault=vault, request_options=request_options)
        return _response.data

    async def stats(
        self, *, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        Cheap orientation: entity counts by type, meetings extracted/total, tasks by status. Call this first to size the knowledge base.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Stats completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.stats()


        asyncio.run(main())
        """
        _response = await self._raw_client.stats(vault=vault, request_options=request_options)
        return _response.data

    async def get_brief(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        kind: typing.Optional[GetBriefRequestKind] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        The latest agent-written brief. kind 'daily' (default) is the current 'what's going on' snapshot of the vault; 'weekly-plan' and 'weekly-digest' mirror the Monday plan and Friday digest e-mails. Good second call after stats for orientation.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        kind : typing.Optional[GetBriefRequestKind]
            Which brief (default daily)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Get Brief completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.get_brief()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_brief(vault=vault, kind=kind, request_options=request_options)
        return _response.data

    async def get_transcript(
        self,
        *,
        meeting_id: str,
        vault: typing.Optional[str] = OMIT,
        offset: typing.Optional[float] = OMIT,
        limit: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Read a meeting transcript sequentially in chunks (complements semantic search). Returns {chunks: [{index, speakers, text}], totalChunks, nextOffset}.

        Parameters
        ----------
        meeting_id : str
            Meeting id from list_meetings

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        offset : typing.Optional[float]
            Chunk offset (default 0)

        limit : typing.Optional[float]
            Chunks per page (default 20, max 50)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Get Transcript completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.get_transcript(
                meeting_id="meetingId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_transcript(
            meeting_id=meeting_id, vault=vault, offset=offset, limit=limit, request_options=request_options
        )
        return _response.data

    async def list_conflicts(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        status: typing.Optional[ListConflictsRequestStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Contradictions detected across the evidence: pairs of credible claims about the same entity that cannot both be true (with speakers and meetings). Default shows open ones needing client validation; filter by status or 'all' to see resolved/dismissed history with notes. Use the id with resolve_conflict.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        status : typing.Optional[ListConflictsRequestStatus]
            Which conflicts (default open)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Conflicts completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.list_conflicts()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_conflicts(vault=vault, status=status, request_options=request_options)
        return _response.data

    async def list_milestones(
        self, *, vault: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> DataResponse:
        """
        Project milestones with task tallies (id, title, target date, tasks done/total). Use to resolve milestone ids before add_task/update_task, or to answer 'what's left in milestone X'.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Milestones completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.list_milestones()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_milestones(vault=vault, request_options=request_options)
        return _response.data

    async def find_person(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        query: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Look someone up in this vault's people registry: name, e-mail, title, organisation. The ONLY authoritative source for an address. never guess one or assume a pattern like first.last@company.com.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        query : typing.Optional[str]
            Name, address or role fragment

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Find Person completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.find_person()


        asyncio.run(main())
        """
        _response = await self._raw_client.find_person(vault=vault, query=query, request_options=request_options)
        return _response.data

    async def list_sent_emails(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        to: typing.Optional[str] = OMIT,
        limit: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Messages this vault's agent already sent, newest first, with the handles needed to reply INSIDE the same conversation (replyToThreadId, inReplyToMessageId). Pass one back to send_email so a reply threads instead of starting a parallel conversation.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        to : typing.Optional[str]
            Narrow to one recipient

        limit : typing.Optional[float]
            1-25, default 10

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            List Sent Emails completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.list_sent_emails()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_sent_emails(
            vault=vault, to=to, limit=limit, request_options=request_options
        )
        return _response.data

    async def find_email_thread(
        self,
        *,
        query: str,
        vault: typing.Optional[str] = OMIT,
        limit: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Search the vault's connected Gmail for an existing conversation, including mail sent before this deployment started logging. Gmail search syntax, e.g. "to:ana@client.com inventory" or "subject:report newer_than:7d". Returns thread ids for send_email's replyToThreadId.

        Parameters
        ----------
        query : str
            Gmail search syntax

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        limit : typing.Optional[float]
            1-20, default 5

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Find Email Thread completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.find_email_thread(
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.find_email_thread(
            query=query, vault=vault, limit=limit, request_options=request_options
        )
        return _response.data

    async def find_artifact(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        query: typing.Optional[str] = OMIT,
        kind: typing.Optional[FindArtifactRequestKind] = OMIT,
        limit: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Find a file that already exists in this vault: something the agent generated (chart, workbook, CSV, report) or a document a member added. Search by title, newest first. Use it BEFORE rebuilding anything, and to get the artifactId that send_email attaches.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        query : typing.Optional[str]
            Words from the title. Omit to list the most recent.

        kind : typing.Optional[FindArtifactRequestKind]
            Narrow to one kind of file

        limit : typing.Optional[float]
            1-25, default 10

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Find Artifact completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.find_artifact()


        asyncio.run(main())
        """
        _response = await self._raw_client.find_artifact(
            vault=vault, query=query, kind=kind, limit=limit, request_options=request_options
        )
        return _response.data

    async def search_agent_memory(
        self,
        *,
        query: str,
        vault: typing.Optional[str] = OMIT,
        person_email: typing.Optional[str] = OMIT,
        limit: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Search the agent's OWN past conversations in this vault. e-mail, MCP and portal chat. for what was already asked, answered or decided. This is conversation history, NOT the knowledge base: use search_knowledge or search_transcripts for what was said in meetings.

        Parameters
        ----------
        query : str
            What was talked about

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        person_email : typing.Optional[str]
            Narrow to exchanges with one person

        limit : typing.Optional[float]
            1-25, default 12

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Search Agent Memory completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.search_agent_memory(
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_agent_memory(
            query=query, vault=vault, person_email=person_email, limit=limit, request_options=request_options
        )
        return _response.data

    async def expand_graph(
        self,
        *,
        entity_id: str,
        vault: typing.Optional[str] = OMIT,
        depth: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DataResponse:
        """
        Graph traversal from an entity: depth 1 = its slim edges; depth 2 = neighborhood expansion (capped at 120 edges, second-hop relations prefixed with the intermediate node). Use to explore paths between areas.

        Parameters
        ----------
        entity_id : str
            Starting entity id

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        depth : typing.Optional[float]
            1 or 2 (default 1)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Expand Graph completed.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.expand_graph(
                entity_id="entityId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.expand_graph(
            entity_id=entity_id, vault=vault, depth=depth, request_options=request_options
        )
        return _response.data
