# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ApiIndexResponseEndpoints(UniversalBaseModel):
    vaults: str
    tools: str
    invoke_tool: typing_extensions.Annotated[str, FieldMetadata(alias="invokeTool"), pydantic.Field(alias="invokeTool")]
    openapi: str
    mcp: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
