# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .find_artifact_request_kind import FindArtifactRequestKind
    from .get_brief_request_kind import GetBriefRequestKind
    from .list_conflicts_request_status import ListConflictsRequestStatus
    from .list_findings_request_sort import ListFindingsRequestSort
    from .list_findings_request_source import ListFindingsRequestSource
    from .list_findings_request_type import ListFindingsRequestType
    from .list_tasks_request_owner import ListTasksRequestOwner
    from .list_tasks_request_status import ListTasksRequestStatus
    from .search_knowledge_request_type import SearchKnowledgeRequestType
_dynamic_imports: typing.Dict[str, str] = {
    "FindArtifactRequestKind": ".find_artifact_request_kind",
    "GetBriefRequestKind": ".get_brief_request_kind",
    "ListConflictsRequestStatus": ".list_conflicts_request_status",
    "ListFindingsRequestSort": ".list_findings_request_sort",
    "ListFindingsRequestSource": ".list_findings_request_source",
    "ListFindingsRequestType": ".list_findings_request_type",
    "ListTasksRequestOwner": ".list_tasks_request_owner",
    "ListTasksRequestStatus": ".list_tasks_request_status",
    "SearchKnowledgeRequestType": ".search_knowledge_request_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "FindArtifactRequestKind",
    "GetBriefRequestKind",
    "ListConflictsRequestStatus",
    "ListFindingsRequestSort",
    "ListFindingsRequestSource",
    "ListFindingsRequestType",
    "ListTasksRequestOwner",
    "ListTasksRequestStatus",
    "SearchKnowledgeRequestType",
]
