# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_index_response import ApiIndexResponse
from ..types.data_response import DataResponse
from .raw_client import AsyncRawMetadataClient, RawMetadataClient


class MetadataClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMetadataClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMetadataClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMetadataClient
        """
        return self._raw_client

    def get_api_index(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiIndexResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiIndexResponse
            The API index.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.metadata.get_api_index()
        """
        _response = self._raw_client.get_api_index(request_options=request_options)
        return _response.data

    def list_tools(self, *, request_options: typing.Optional[RequestOptions] = None) -> DataResponse:
        """
        Return the live tool catalog and JSON input schemas used by both the REST API and MCP.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            The live tool catalog.

        Examples
        --------
        from openantares import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.metadata.list_tools()
        """
        _response = self._raw_client.list_tools(request_options=request_options)
        return _response.data


class AsyncMetadataClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMetadataClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMetadataClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMetadataClient
        """
        return self._raw_client

    async def get_api_index(self, *, request_options: typing.Optional[RequestOptions] = None) -> ApiIndexResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiIndexResponse
            The API index.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.metadata.get_api_index()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_api_index(request_options=request_options)
        return _response.data

    async def list_tools(self, *, request_options: typing.Optional[RequestOptions] = None) -> DataResponse:
        """
        Return the live tool catalog and JSON input schemas used by both the REST API and MCP.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            The live tool catalog.

        Examples
        --------
        import asyncio

        from openantares import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.metadata.list_tools()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_tools(request_options=request_options)
        return _response.data
