# This file was auto-generated by Fern from our API Definition.

import typing

ListFindingsRequestType = typing.Union[
    typing.Literal["department", "person", "process", "system", "problem", "opportunity", "kpi"], typing.Any
]
