# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.data_response import DataResponse
from .raw_client import AsyncRawVaultsClient, RawVaultsClient


class VaultsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVaultsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVaultsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVaultsClient
        """
        return self._raw_client

    def list_vaults(self, *, request_options: typing.Optional[RequestOptions] = None) -> DataResponse:
        """
        List the vaults the credential holder may access. If more than one vault is returned, pass the exact vault id to later calls.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Authorized vaults.

        Examples
        --------
        from alpha import Alpha

        client = Alpha(
            token="YOUR_TOKEN",
        )
        client.vaults.list_vaults()
        """
        _response = self._raw_client.list_vaults(request_options=request_options)
        return _response.data


class AsyncVaultsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVaultsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVaultsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVaultsClient
        """
        return self._raw_client

    async def list_vaults(self, *, request_options: typing.Optional[RequestOptions] = None) -> DataResponse:
        """
        List the vaults the credential holder may access. If more than one vault is returned, pass the exact vault id to later calls.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DataResponse
            Authorized vaults.

        Examples
        --------
        import asyncio

        from alpha import AsyncAlpha

        client = AsyncAlpha(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.vaults.list_vaults()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_vaults(request_options=request_options)
        return _response.data
