# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        ApiError,
        ApiIndexResponse,
        ApiIndexResponseEndpoints,
        DataResponse,
        DataResponseData,
        ErrorResponse,
    )
    from .errors import BadRequestError, ForbiddenError, NotFoundError, TooManyRequestsError, UnauthorizedError
    from . import actions, knowledge, metadata, vaults
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .actions import (
        AddTaskRequestChecklistItem,
        AddTaskRequestEstimate,
        AddTaskRequestPriority,
        ExportReportRequestDataset,
        ExportReportRequestFormat,
        ResolveConflictRequestStatus,
        SendEmailRequestSendAs,
        UpdateTaskRequestChecklistItem,
        UpdateTaskRequestEstimate,
        UpdateTaskRequestIdentifier,
        UpdateTaskRequestPriority,
        UpdateTaskRequestStatus,
    )
    from .client import Alpha, AsyncAlpha
    from .environment import AlphaEnvironment
    from .knowledge import (
        FindArtifactRequestKind,
        GetBriefRequestKind,
        ListConflictsRequestStatus,
        ListFindingsRequestSort,
        ListFindingsRequestSource,
        ListFindingsRequestType,
        ListTasksRequestStatus,
        SearchKnowledgeRequestType,
    )
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "AddTaskRequestChecklistItem": ".actions",
    "AddTaskRequestEstimate": ".actions",
    "AddTaskRequestPriority": ".actions",
    "Alpha": ".client",
    "AlphaEnvironment": ".environment",
    "ApiError": ".types",
    "ApiIndexResponse": ".types",
    "ApiIndexResponseEndpoints": ".types",
    "AsyncAlpha": ".client",
    "BadRequestError": ".errors",
    "DataResponse": ".types",
    "DataResponseData": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ErrorResponse": ".types",
    "ExportReportRequestDataset": ".actions",
    "ExportReportRequestFormat": ".actions",
    "FindArtifactRequestKind": ".knowledge",
    "ForbiddenError": ".errors",
    "GetBriefRequestKind": ".knowledge",
    "ListConflictsRequestStatus": ".knowledge",
    "ListFindingsRequestSort": ".knowledge",
    "ListFindingsRequestSource": ".knowledge",
    "ListFindingsRequestType": ".knowledge",
    "ListTasksRequestStatus": ".knowledge",
    "NotFoundError": ".errors",
    "ResolveConflictRequestStatus": ".actions",
    "SearchKnowledgeRequestType": ".knowledge",
    "SendEmailRequestSendAs": ".actions",
    "TooManyRequestsError": ".errors",
    "UnauthorizedError": ".errors",
    "UpdateTaskRequestChecklistItem": ".actions",
    "UpdateTaskRequestEstimate": ".actions",
    "UpdateTaskRequestIdentifier": ".actions",
    "UpdateTaskRequestPriority": ".actions",
    "UpdateTaskRequestStatus": ".actions",
    "__version__": ".version",
    "actions": ".actions",
    "knowledge": ".knowledge",
    "metadata": ".metadata",
    "vaults": ".vaults",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AddTaskRequestChecklistItem",
    "AddTaskRequestEstimate",
    "AddTaskRequestPriority",
    "Alpha",
    "AlphaEnvironment",
    "ApiError",
    "ApiIndexResponse",
    "ApiIndexResponseEndpoints",
    "AsyncAlpha",
    "BadRequestError",
    "DataResponse",
    "DataResponseData",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ErrorResponse",
    "ExportReportRequestDataset",
    "ExportReportRequestFormat",
    "FindArtifactRequestKind",
    "ForbiddenError",
    "GetBriefRequestKind",
    "ListConflictsRequestStatus",
    "ListFindingsRequestSort",
    "ListFindingsRequestSource",
    "ListFindingsRequestType",
    "ListTasksRequestStatus",
    "NotFoundError",
    "ResolveConflictRequestStatus",
    "SearchKnowledgeRequestType",
    "SendEmailRequestSendAs",
    "TooManyRequestsError",
    "UnauthorizedError",
    "UpdateTaskRequestChecklistItem",
    "UpdateTaskRequestEstimate",
    "UpdateTaskRequestIdentifier",
    "UpdateTaskRequestPriority",
    "UpdateTaskRequestStatus",
    "__version__",
    "actions",
    "knowledge",
    "metadata",
    "vaults",
]
