# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .add_task_request_checklist_item import AddTaskRequestChecklistItem
    from .add_task_request_estimate import AddTaskRequestEstimate
    from .add_task_request_owner import AddTaskRequestOwner
    from .add_task_request_priority import AddTaskRequestPriority
    from .export_report_request_dataset import ExportReportRequestDataset
    from .export_report_request_format import ExportReportRequestFormat
    from .resolve_conflict_request_status import ResolveConflictRequestStatus
    from .send_email_request_send_as import SendEmailRequestSendAs
    from .update_task_request_checklist_item import UpdateTaskRequestChecklistItem
    from .update_task_request_estimate import UpdateTaskRequestEstimate
    from .update_task_request_identifier import UpdateTaskRequestIdentifier
    from .update_task_request_owner import UpdateTaskRequestOwner
    from .update_task_request_priority import UpdateTaskRequestPriority
    from .update_task_request_status import UpdateTaskRequestStatus
_dynamic_imports: typing.Dict[str, str] = {
    "AddTaskRequestChecklistItem": ".add_task_request_checklist_item",
    "AddTaskRequestEstimate": ".add_task_request_estimate",
    "AddTaskRequestOwner": ".add_task_request_owner",
    "AddTaskRequestPriority": ".add_task_request_priority",
    "ExportReportRequestDataset": ".export_report_request_dataset",
    "ExportReportRequestFormat": ".export_report_request_format",
    "ResolveConflictRequestStatus": ".resolve_conflict_request_status",
    "SendEmailRequestSendAs": ".send_email_request_send_as",
    "UpdateTaskRequestChecklistItem": ".update_task_request_checklist_item",
    "UpdateTaskRequestEstimate": ".update_task_request_estimate",
    "UpdateTaskRequestIdentifier": ".update_task_request_identifier",
    "UpdateTaskRequestOwner": ".update_task_request_owner",
    "UpdateTaskRequestPriority": ".update_task_request_priority",
    "UpdateTaskRequestStatus": ".update_task_request_status",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AddTaskRequestChecklistItem",
    "AddTaskRequestEstimate",
    "AddTaskRequestOwner",
    "AddTaskRequestPriority",
    "ExportReportRequestDataset",
    "ExportReportRequestFormat",
    "ResolveConflictRequestStatus",
    "SendEmailRequestSendAs",
    "UpdateTaskRequestChecklistItem",
    "UpdateTaskRequestEstimate",
    "UpdateTaskRequestIdentifier",
    "UpdateTaskRequestOwner",
    "UpdateTaskRequestPriority",
    "UpdateTaskRequestStatus",
]
