# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.data_response import DataResponse
from ..types.error_response import ErrorResponse
from .types.add_task_request_checklist_item import AddTaskRequestChecklistItem
from .types.add_task_request_estimate import AddTaskRequestEstimate
from .types.add_task_request_priority import AddTaskRequestPriority
from .types.export_report_request_dataset import ExportReportRequestDataset
from .types.export_report_request_format import ExportReportRequestFormat
from .types.resolve_conflict_request_status import ResolveConflictRequestStatus
from .types.send_email_request_send_as import SendEmailRequestSendAs
from .types.update_task_request_checklist_item import UpdateTaskRequestChecklistItem
from .types.update_task_request_estimate import UpdateTaskRequestEstimate
from .types.update_task_request_identifier import UpdateTaskRequestIdentifier
from .types.update_task_request_priority import UpdateTaskRequestPriority
from .types.update_task_request_status import UpdateTaskRequestStatus
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawActionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def resolve_conflict(
        self,
        *,
        conflict_id: str,
        status: ResolveConflictRequestStatus,
        vault: typing.Optional[str] = OMIT,
        note: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DataResponse]:
        """
        Close out a contradiction by id (from list_conflicts): status 'resolved' (validated with the client. say what the truth turned out to be in the note) or 'dismissed' (duplicate, transcription noise, not a real conflict. note why). Passing 'open' reopens one. Requires a manager API key.

        Parameters
        ----------
        conflict_id : str
            Conflict id from list_conflicts

        status : ResolveConflictRequestStatus

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        note : typing.Optional[str]
            Resolution note: the validated answer, or why it was dismissed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DataResponse]
            Resolve Conflict completed.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/resolve_conflict",
            method="POST",
            json={
                "vault": vault,
                "conflictId": conflict_id,
                "status": status,
                "note": note,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_task(
        self,
        *,
        title: str,
        vault: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        assignee_name: typing.Optional[str] = OMIT,
        estimate: typing.Optional[AddTaskRequestEstimate] = OMIT,
        priority: typing.Optional[AddTaskRequestPriority] = OMIT,
        labels: typing.Optional[typing.Sequence[str]] = OMIT,
        checklist: typing.Optional[typing.Sequence[AddTaskRequestChecklistItem]] = OMIT,
        due_date: typing.Optional[str] = OMIT,
        milestone_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DataResponse]:
        """
        Create a task on the vault's board. The owner may be a person's name or a company placeholder. Supports the full kanban surface: t-shirt estimate, priority, labels, checklist, due date and milestone (resolve ids with list_milestones). Requires a manager API key.

        Parameters
        ----------
        title : str
            Short actionable title (short and actionable)

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        description : typing.Optional[str]
            Optional detail

        assignee_name : typing.Optional[str]
            Responsible person or company

        estimate : typing.Optional[AddTaskRequestEstimate]
            T-shirt effort size

        priority : typing.Optional[AddTaskRequestPriority]

        labels : typing.Optional[typing.Sequence[str]]

        checklist : typing.Optional[typing.Sequence[AddTaskRequestChecklistItem]]

        due_date : typing.Optional[str]
            ISO date, e.g. 2026-08-15

        milestone_id : typing.Optional[str]
            Milestone id from list_milestones

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DataResponse]
            Add Task completed.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/add_task",
            method="POST",
            json={
                "vault": vault,
                "title": title,
                "description": description,
                "assigneeName": assignee_name,
                "estimate": estimate,
                "priority": priority,
                "labels": labels,
                "checklist": convert_and_respect_annotation_metadata(
                    object_=checklist, annotation=typing.Sequence[AddTaskRequestChecklistItem], direction="write"
                ),
                "dueDate": due_date,
                "milestoneId": milestone_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_task(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        identifier: typing.Optional[UpdateTaskRequestIdentifier] = OMIT,
        task_id: typing.Optional[str] = OMIT,
        title: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        status: typing.Optional[UpdateTaskRequestStatus] = OMIT,
        assignee_name: typing.Optional[str] = OMIT,
        estimate: typing.Optional[UpdateTaskRequestEstimate] = OMIT,
        priority: typing.Optional[UpdateTaskRequestPriority] = OMIT,
        labels: typing.Optional[typing.Sequence[str]] = OMIT,
        checklist: typing.Optional[typing.Sequence[UpdateTaskRequestChecklistItem]] = OMIT,
        due_date: typing.Optional[str] = OMIT,
        milestone_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DataResponse]:
        """
        Edit an existing task by its board identifier (for example 'ACME-5', or just 5; the prefix is whatever this vault uses) or by taskId from list_tasks. Fields: status, named owner, t-shirt estimate, priority, labels, checklist, due date, milestone, title and description. Pass null to clear a clearable field (estimate, dueDate, milestoneId, assigneeName, description). Requires a manager API key.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        identifier : typing.Optional[UpdateTaskRequestIdentifier]
            Board reference: e.g. 'ACME-5', or just 5

        task_id : typing.Optional[str]
            Task id from list_tasks (alternative to identifier)

        title : typing.Optional[str]

        description : typing.Optional[str]

        status : typing.Optional[UpdateTaskRequestStatus]

        assignee_name : typing.Optional[str]
            Responsible person or company; null clears it

        estimate : typing.Optional[UpdateTaskRequestEstimate]
            T-shirt effort size; null clears it

        priority : typing.Optional[UpdateTaskRequestPriority]

        labels : typing.Optional[typing.Sequence[str]]
            Replaces the label list ([] clears)

        checklist : typing.Optional[typing.Sequence[UpdateTaskRequestChecklistItem]]
            Replaces the checklist ([] clears)

        due_date : typing.Optional[str]
            ISO date; null clears

        milestone_id : typing.Optional[str]
            Milestone id from list_milestones; null clears

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DataResponse]
            Update Task completed.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/update_task",
            method="POST",
            json={
                "vault": vault,
                "identifier": convert_and_respect_annotation_metadata(
                    object_=identifier, annotation=UpdateTaskRequestIdentifier, direction="write"
                ),
                "taskId": task_id,
                "title": title,
                "description": description,
                "status": status,
                "assigneeName": assignee_name,
                "estimate": estimate,
                "priority": priority,
                "labels": labels,
                "checklist": convert_and_respect_annotation_metadata(
                    object_=checklist, annotation=typing.Sequence[UpdateTaskRequestChecklistItem], direction="write"
                ),
                "dueDate": due_date,
                "milestoneId": milestone_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def send_email(
        self,
        *,
        to: str,
        subject: str,
        body: str,
        vault: typing.Optional[str] = OMIT,
        cc: typing.Optional[typing.Sequence[str]] = OMIT,
        attachment_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        send_as: typing.Optional[SendEmailRequestSendAs] = OMIT,
        reply_to_thread_id: typing.Optional[str] = OMIT,
        in_reply_to_message_id: typing.Optional[str] = OMIT,
        as_draft: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DataResponse]:
        """
        Send an e-mail from the vault agent's mailbox to a VAULT MEMBER or registered stakeholder. Can carry files: pass artifact ids from find_artifact. Can also reply INSIDE an existing thread, or be left as a draft in the connected Gmail account for a person to review and send. Requires a manager API key.

        Parameters
        ----------
        to : str
            Recipient (must belong to this vault)

        subject : str

        body : str
            Plain-text body

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        cc : typing.Optional[typing.Sequence[str]]
            Copied recipients, subject to the same vault check as `to`

        attachment_ids : typing.Optional[typing.Sequence[str]]
            artifactId values from find_artifact. Files only, never URLs.

        send_as : typing.Optional[SendEmailRequestSendAs]
            'agent' (default) sends from the vault agent's address and takes several attachments; 'me' sends from the vault's connected Gmail and takes one.

        reply_to_thread_id : typing.Optional[str]
            Gmail thread id, to reply inside an existing conversation

        in_reply_to_message_id : typing.Optional[str]
            Message-ID of an earlier agent e-mail, to thread the reply

        as_draft : typing.Optional[bool]
            Leave it in the connected Gmail's Drafts instead of sending. Nothing goes out.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DataResponse]
            Send Email completed.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/send_email",
            method="POST",
            json={
                "vault": vault,
                "to": to,
                "subject": subject,
                "body": body,
                "cc": cc,
                "attachmentIds": attachment_ids,
                "sendAs": send_as,
                "replyToThreadId": reply_to_thread_id,
                "inReplyToMessageId": in_reply_to_message_id,
                "asDraft": as_draft,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def export_workbook(
        self,
        *,
        title: str,
        sheets: typing.Sequence[typing.Dict[str, typing.Any]],
        vault: typing.Optional[str] = OMIT,
        sources: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DataResponse]:
        """
        Build a styled multi-sheet Excel workbook (.xlsx) from rows you provide, store it in this vault, and return a url plus an artifactId that send_email can attach. Use it when the answer is a table someone will sort, filter or forward. Formatting, freezing and the provenance sheet are automatic. Requires a manager API key, since it stores a file.

        Parameters
        ----------
        title : str
            What the workbook is about

        sheets : typing.Sequence[typing.Dict[str, typing.Any]]
            One entry per tab: {name, columns:[{header,key,numFmt?}], rows:[{<key>: value}]}

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        sources : typing.Optional[str]
            Where the numbers came from; goes on the provenance sheet

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DataResponse]
            Export Workbook completed.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/export_workbook",
            method="POST",
            json={
                "vault": vault,
                "title": title,
                "sheets": sheets,
                "sources": sources,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def export_report(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        dataset: typing.Optional[ExportReportRequestDataset] = OMIT,
        format: typing.Optional[ExportReportRequestFormat] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DataResponse]:
        """
        Export a whole dataset from this vault as a file: every finding, or every contradiction, as xlsx, csv or PDF. The only path that produces a PDF. For a table you assembled yourself, use export_workbook. Returns a url and an artifactId that send_email can attach. Requires a manager API key, since it stores a file.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        dataset : typing.Optional[ExportReportRequestDataset]
            Default findings

        format : typing.Optional[ExportReportRequestFormat]
            Default xlsx

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DataResponse]
            Export Report completed.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/export_report",
            method="POST",
            json={
                "vault": vault,
                "dataset": dataset,
                "format": format,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def render_chart(
        self,
        *,
        title: str,
        vega_lite_spec: typing.Dict[str, typing.Any],
        vault: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DataResponse]:
        """
        Render a chart PNG from a Vega-Lite v5 spec with the data inline, and store it as an artifact in this vault. Returns a url to embed and an artifactId that send_email can attach. Do not set colors: the vault's theme is applied automatically. Match the mark to the question. anything over time is a line, a ranking is a sorted horizontal bar, part-of-whole is an arc. Requires a manager API key, since it stores a file.

        Parameters
        ----------
        title : str
            Chart title, shown on the image

        vega_lite_spec : typing.Dict[str, typing.Any]
            Complete Vega-Lite v5 spec with inline data, e.g. {"data":{"values":[{"month":"2026-05","team":"Logistics","mentions":11}]},"mark":"line","encoding":{...}}. For month buckets set "timeUnit":"yearmonth" or the axis is labelled by day.

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DataResponse]
            Render Chart completed.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/render_chart",
            method="POST",
            json={
                "vault": vault,
                "title": title,
                "vega_lite_spec": vega_lite_spec,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def schedule_meeting(
        self,
        *,
        title: str,
        start_iso: str,
        attendees: typing.Sequence[str],
        vault: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        duration_minutes: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DataResponse]:
        """
        Create a Google Calendar event with a Meet link via the project's connected calendar. Requires a manager API key.

        Parameters
        ----------
        title : str

        start_iso : str
            ISO 8601 with offset, e.g. 2026-07-22T14:00:00-03:00

        attendees : typing.Sequence[str]
            Attendee e-mails

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        description : typing.Optional[str]

        duration_minutes : typing.Optional[float]
            15 to 120 (default 30)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DataResponse]
            Schedule Meeting completed.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools/schedule_meeting",
            method="POST",
            json={
                "vault": vault,
                "title": title,
                "description": description,
                "startIso": start_iso,
                "durationMinutes": duration_minutes,
                "attendees": attendees,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawActionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def resolve_conflict(
        self,
        *,
        conflict_id: str,
        status: ResolveConflictRequestStatus,
        vault: typing.Optional[str] = OMIT,
        note: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DataResponse]:
        """
        Close out a contradiction by id (from list_conflicts): status 'resolved' (validated with the client. say what the truth turned out to be in the note) or 'dismissed' (duplicate, transcription noise, not a real conflict. note why). Passing 'open' reopens one. Requires a manager API key.

        Parameters
        ----------
        conflict_id : str
            Conflict id from list_conflicts

        status : ResolveConflictRequestStatus

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        note : typing.Optional[str]
            Resolution note: the validated answer, or why it was dismissed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DataResponse]
            Resolve Conflict completed.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/resolve_conflict",
            method="POST",
            json={
                "vault": vault,
                "conflictId": conflict_id,
                "status": status,
                "note": note,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_task(
        self,
        *,
        title: str,
        vault: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        assignee_name: typing.Optional[str] = OMIT,
        estimate: typing.Optional[AddTaskRequestEstimate] = OMIT,
        priority: typing.Optional[AddTaskRequestPriority] = OMIT,
        labels: typing.Optional[typing.Sequence[str]] = OMIT,
        checklist: typing.Optional[typing.Sequence[AddTaskRequestChecklistItem]] = OMIT,
        due_date: typing.Optional[str] = OMIT,
        milestone_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DataResponse]:
        """
        Create a task on the vault's board. The owner may be a person's name or a company placeholder. Supports the full kanban surface: t-shirt estimate, priority, labels, checklist, due date and milestone (resolve ids with list_milestones). Requires a manager API key.

        Parameters
        ----------
        title : str
            Short actionable title (short and actionable)

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        description : typing.Optional[str]
            Optional detail

        assignee_name : typing.Optional[str]
            Responsible person or company

        estimate : typing.Optional[AddTaskRequestEstimate]
            T-shirt effort size

        priority : typing.Optional[AddTaskRequestPriority]

        labels : typing.Optional[typing.Sequence[str]]

        checklist : typing.Optional[typing.Sequence[AddTaskRequestChecklistItem]]

        due_date : typing.Optional[str]
            ISO date, e.g. 2026-08-15

        milestone_id : typing.Optional[str]
            Milestone id from list_milestones

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DataResponse]
            Add Task completed.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/add_task",
            method="POST",
            json={
                "vault": vault,
                "title": title,
                "description": description,
                "assigneeName": assignee_name,
                "estimate": estimate,
                "priority": priority,
                "labels": labels,
                "checklist": convert_and_respect_annotation_metadata(
                    object_=checklist, annotation=typing.Sequence[AddTaskRequestChecklistItem], direction="write"
                ),
                "dueDate": due_date,
                "milestoneId": milestone_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_task(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        identifier: typing.Optional[UpdateTaskRequestIdentifier] = OMIT,
        task_id: typing.Optional[str] = OMIT,
        title: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        status: typing.Optional[UpdateTaskRequestStatus] = OMIT,
        assignee_name: typing.Optional[str] = OMIT,
        estimate: typing.Optional[UpdateTaskRequestEstimate] = OMIT,
        priority: typing.Optional[UpdateTaskRequestPriority] = OMIT,
        labels: typing.Optional[typing.Sequence[str]] = OMIT,
        checklist: typing.Optional[typing.Sequence[UpdateTaskRequestChecklistItem]] = OMIT,
        due_date: typing.Optional[str] = OMIT,
        milestone_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DataResponse]:
        """
        Edit an existing task by its board identifier (for example 'ACME-5', or just 5; the prefix is whatever this vault uses) or by taskId from list_tasks. Fields: status, named owner, t-shirt estimate, priority, labels, checklist, due date, milestone, title and description. Pass null to clear a clearable field (estimate, dueDate, milestoneId, assigneeName, description). Requires a manager API key.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        identifier : typing.Optional[UpdateTaskRequestIdentifier]
            Board reference: e.g. 'ACME-5', or just 5

        task_id : typing.Optional[str]
            Task id from list_tasks (alternative to identifier)

        title : typing.Optional[str]

        description : typing.Optional[str]

        status : typing.Optional[UpdateTaskRequestStatus]

        assignee_name : typing.Optional[str]
            Responsible person or company; null clears it

        estimate : typing.Optional[UpdateTaskRequestEstimate]
            T-shirt effort size; null clears it

        priority : typing.Optional[UpdateTaskRequestPriority]

        labels : typing.Optional[typing.Sequence[str]]
            Replaces the label list ([] clears)

        checklist : typing.Optional[typing.Sequence[UpdateTaskRequestChecklistItem]]
            Replaces the checklist ([] clears)

        due_date : typing.Optional[str]
            ISO date; null clears

        milestone_id : typing.Optional[str]
            Milestone id from list_milestones; null clears

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DataResponse]
            Update Task completed.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/update_task",
            method="POST",
            json={
                "vault": vault,
                "identifier": convert_and_respect_annotation_metadata(
                    object_=identifier, annotation=UpdateTaskRequestIdentifier, direction="write"
                ),
                "taskId": task_id,
                "title": title,
                "description": description,
                "status": status,
                "assigneeName": assignee_name,
                "estimate": estimate,
                "priority": priority,
                "labels": labels,
                "checklist": convert_and_respect_annotation_metadata(
                    object_=checklist, annotation=typing.Sequence[UpdateTaskRequestChecklistItem], direction="write"
                ),
                "dueDate": due_date,
                "milestoneId": milestone_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def send_email(
        self,
        *,
        to: str,
        subject: str,
        body: str,
        vault: typing.Optional[str] = OMIT,
        cc: typing.Optional[typing.Sequence[str]] = OMIT,
        attachment_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        send_as: typing.Optional[SendEmailRequestSendAs] = OMIT,
        reply_to_thread_id: typing.Optional[str] = OMIT,
        in_reply_to_message_id: typing.Optional[str] = OMIT,
        as_draft: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DataResponse]:
        """
        Send an e-mail from the vault agent's mailbox to a VAULT MEMBER or registered stakeholder. Can carry files: pass artifact ids from find_artifact. Can also reply INSIDE an existing thread, or be left as a draft in the connected Gmail account for a person to review and send. Requires a manager API key.

        Parameters
        ----------
        to : str
            Recipient (must belong to this vault)

        subject : str

        body : str
            Plain-text body

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        cc : typing.Optional[typing.Sequence[str]]
            Copied recipients, subject to the same vault check as `to`

        attachment_ids : typing.Optional[typing.Sequence[str]]
            artifactId values from find_artifact. Files only, never URLs.

        send_as : typing.Optional[SendEmailRequestSendAs]
            'agent' (default) sends from the vault agent's address and takes several attachments; 'me' sends from the vault's connected Gmail and takes one.

        reply_to_thread_id : typing.Optional[str]
            Gmail thread id, to reply inside an existing conversation

        in_reply_to_message_id : typing.Optional[str]
            Message-ID of an earlier agent e-mail, to thread the reply

        as_draft : typing.Optional[bool]
            Leave it in the connected Gmail's Drafts instead of sending. Nothing goes out.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DataResponse]
            Send Email completed.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/send_email",
            method="POST",
            json={
                "vault": vault,
                "to": to,
                "subject": subject,
                "body": body,
                "cc": cc,
                "attachmentIds": attachment_ids,
                "sendAs": send_as,
                "replyToThreadId": reply_to_thread_id,
                "inReplyToMessageId": in_reply_to_message_id,
                "asDraft": as_draft,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def export_workbook(
        self,
        *,
        title: str,
        sheets: typing.Sequence[typing.Dict[str, typing.Any]],
        vault: typing.Optional[str] = OMIT,
        sources: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DataResponse]:
        """
        Build a styled multi-sheet Excel workbook (.xlsx) from rows you provide, store it in this vault, and return a url plus an artifactId that send_email can attach. Use it when the answer is a table someone will sort, filter or forward. Formatting, freezing and the provenance sheet are automatic. Requires a manager API key, since it stores a file.

        Parameters
        ----------
        title : str
            What the workbook is about

        sheets : typing.Sequence[typing.Dict[str, typing.Any]]
            One entry per tab: {name, columns:[{header,key,numFmt?}], rows:[{<key>: value}]}

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        sources : typing.Optional[str]
            Where the numbers came from; goes on the provenance sheet

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DataResponse]
            Export Workbook completed.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/export_workbook",
            method="POST",
            json={
                "vault": vault,
                "title": title,
                "sheets": sheets,
                "sources": sources,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def export_report(
        self,
        *,
        vault: typing.Optional[str] = OMIT,
        dataset: typing.Optional[ExportReportRequestDataset] = OMIT,
        format: typing.Optional[ExportReportRequestFormat] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DataResponse]:
        """
        Export a whole dataset from this vault as a file: every finding, or every contradiction, as xlsx, csv or PDF. The only path that produces a PDF. For a table you assembled yourself, use export_workbook. Returns a url and an artifactId that send_email can attach. Requires a manager API key, since it stores a file.

        Parameters
        ----------
        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        dataset : typing.Optional[ExportReportRequestDataset]
            Default findings

        format : typing.Optional[ExportReportRequestFormat]
            Default xlsx

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DataResponse]
            Export Report completed.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/export_report",
            method="POST",
            json={
                "vault": vault,
                "dataset": dataset,
                "format": format,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def render_chart(
        self,
        *,
        title: str,
        vega_lite_spec: typing.Dict[str, typing.Any],
        vault: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DataResponse]:
        """
        Render a chart PNG from a Vega-Lite v5 spec with the data inline, and store it as an artifact in this vault. Returns a url to embed and an artifactId that send_email can attach. Do not set colors: the vault's theme is applied automatically. Match the mark to the question. anything over time is a line, a ranking is a sorted horizontal bar, part-of-whole is an arc. Requires a manager API key, since it stores a file.

        Parameters
        ----------
        title : str
            Chart title, shown on the image

        vega_lite_spec : typing.Dict[str, typing.Any]
            Complete Vega-Lite v5 spec with inline data, e.g. {"data":{"values":[{"month":"2026-05","team":"Logistics","mentions":11}]},"mark":"line","encoding":{...}}. For month buckets set "timeUnit":"yearmonth" or the axis is labelled by day.

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DataResponse]
            Render Chart completed.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/render_chart",
            method="POST",
            json={
                "vault": vault,
                "title": title,
                "vega_lite_spec": vega_lite_spec,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def schedule_meeting(
        self,
        *,
        title: str,
        start_iso: str,
        attendees: typing.Sequence[str],
        vault: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        duration_minutes: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DataResponse]:
        """
        Create a Google Calendar event with a Meet link via the project's connected calendar. Requires a manager API key.

        Parameters
        ----------
        title : str

        start_iso : str
            ISO 8601 with offset, e.g. 2026-07-22T14:00:00-03:00

        attendees : typing.Sequence[str]
            Attendee e-mails

        vault : typing.Optional[str]
            Exact vault id or name from list_vaults. Required whenever the key can reach more than one vault; never guess or use one client's vault for another.

        description : typing.Optional[str]

        duration_minutes : typing.Optional[float]
            15 to 120 (default 30)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DataResponse]
            Schedule Meeting completed.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools/schedule_meeting",
            method="POST",
            json={
                "vault": vault,
                "title": title,
                "description": description,
                "startIso": start_iso,
                "durationMinutes": duration_minutes,
                "attendees": attendees,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DataResponse,
                    parse_obj_as(
                        type_=DataResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
